package dev.busung.s25uroot

import android.content.Context
import android.content.Intent
import android.provider.Settings
import android.util.Log

/**
 * Puts Developer options in front of the user.
 *
 * Pairing is the one step of this app that cannot be done from inside it. The six-digit code is
 * generated by Android's own dialog - the app only ever receives it - and the wireless-debugging
 * switch that dialog needs lives in a screen no app may write to directly. Naming that screen in a
 * notification, which is what this used to do, asks the user to find Developer options, then
 * Wireless debugging, then the right entry, from memory, while a code expires.
 *
 * So the app opens it, and the reason this is more than one line is that the platform documents
 * [Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS] without promising a screen behind it: this is a
 * Samsung build whose developer dashboard is not the AOSP class name. The chain is tried in order and
 * its last entry is Settings itself, which exists wherever a Settings app does - so the worst case is
 * landing one screen away from the target rather than on nothing at all.
 *
 * Nothing here is queried before it is launched. Package visibility would let `resolveActivity` say
 * "no" about a screen that would have opened, so each attempt is made and only a launch that actually
 * failed moves the chain on.
 */
internal object DeveloperOptions {

    /**
     * One place worth opening: an action, or an explicit component, never both.
     *
     * Plain data, so the order and the fallbacks can be tested without a device.
     */
    internal data class Target(val action: String?, val component: String?) {
        init {
            require((action == null) != (component == null)) {
                "a target is either an action or a component"
            }
            component?.let {
                require(it.startsWith(SETTINGS_PACKAGE)) {
                    "a component target is a class in $SETTINGS_PACKAGE"
                }
            }
        }

        /** What a log line should call this target. */
        val label: String get() = action ?: component!!
    }

    private const val SETTINGS_PACKAGE = "com.android.settings"
    private const val TAG = "RootMyGalaxySettings"

    /**
     * The chain, in order.
     *
     * Two component fallbacks because the dashboard's name differs between builds: Samsung's One UI
     * activity and the AOSP one. Both are tried before Settings home, which is the one screen that is
     * certain to exist and is still a step towards the target - Developer options is on its front page.
     */
    internal fun targets(): List<Target> = listOf(
        Target(Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS, null),
        Target(null, "$SETTINGS_PACKAGE.Settings\$DevelopmentSettingsActivity"),
        Target(null, "$SETTINGS_PACKAGE.Settings\$DevelopmentSettingsDashboardActivity"),
        Target(Settings.ACTION_SETTINGS, null),
    )

    /** The first target [canOpen] accepts, or null when none of them can be opened. */
    internal fun <T> firstOpenable(targets: List<T>, canOpen: (T) -> Boolean): T? =
        targets.firstOrNull(canOpen)

    private fun intent(target: Target): Intent =
        (target.action?.let { Intent(it) } ?: Intent().setClassName(SETTINGS_PACKAGE, target.component!!))
            .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)

    /**
     * Opens Developer options, and reports whether any screen in the chain opened.
     *
     * A false here is worth telling the user about rather than swallowing, because the whole point of
     * this call is that they should be looking at a settings screen afterwards.
     */
    fun open(context: Context): Boolean {
        val opened = firstOpenable(targets()) { target ->
            runCatching { context.startActivity(intent(target)) }
                .onFailure { error ->
                    // An action with no activity behind it and a component this build does not have
                    // are both ActivityNotFoundException, and both mean "try the next one".
                    Log.i(TAG, "Could not open ${target.label}: ${error.message}")
                }
                .isSuccess
        }
        if (opened == null) Log.w(TAG, "No Settings screen in the chain could be opened")
        return opened != null
    }
}

/**
 * What opens Developer options when the notification's action is tapped.
 *
 * A broadcast rather than `PendingIntent.getActivity`, so the notification gets the same fallback
 * chain as the app does. A pending intent is built around one immutable Intent, and the entry it would
 * carry is the action a build without that screen would silently refuse.
 */
class OpenDeveloperOptionsReceiver : android.content.BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != ACTION_OPEN_DEVELOPER_OPTIONS) return
        DeveloperOptions.open(context)
    }

    companion object {
        const val ACTION_OPEN_DEVELOPER_OPTIONS =
            "dev.busung.s25uroot.action.OPEN_DEVELOPER_OPTIONS"
    }
}
